name: 'SnappyCache Github Build And Test'
run-name: ${{ github.actor }} is running build and test of SnappyCache
on:
  push:
  schedule:
    - cron: '20 2 1,15 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    name: phpunit tests
    steps:
      - name: Run phpunit action
        uses: ./actions/snappycache-docker-test-action
      - name: Checkout
        uses: actions/checkout@v4
